version: '3.8'

services:
  backend:
    build: .
    container_name: gemini_backend_service
    ports:
      - "3000:3000"
    env_file:
      - .env # Load environment variables from .env file
    restart: unless-stopped
    healthcheck:
      # Use the healthcheck defined in the Dockerfile
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3 